//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentCustomer()
        {
            this.AssessmentCustomerQuestionAnswer = new HashSet<AssessmentCustomerQuestionAnswer>();
            this.AssessmentOfferType = new HashSet<AssessmentOfferType>();
            this.AssessmentTransactionType = new HashSet<AssessmentTransactionType>();
            this.AssessmentCustomerWebScan = new HashSet<AssessmentCustomerWebScan>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid AssessmentTypeId { get; set; }
        public System.Guid AssessorId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string Site { get; set; }
        public string Project { get; set; }
        public string Segment { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<System.Guid> VersionId { get; set; }
        public string ScaniaDepartment { get; set; }
        public Nullable<System.Guid> CaseTypeId { get; set; }
        public Nullable<System.Guid> SectorId { get; set; }
        public string ResponibleSalesPerson { get; set; }
        public Nullable<decimal> RiskIndication { get; set; }
        public string Comment { get; set; }
        public bool IsComplete { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public System.Guid ChangedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual CaseType CaseType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual User User2 { get; set; }
        public virtual Version Version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCustomerQuestionAnswer> AssessmentCustomerQuestionAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentOfferType> AssessmentOfferType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTransactionType> AssessmentTransactionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCustomerWebScan> AssessmentCustomerWebScan { get; set; }
    }
}
