//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentCustomerWebScan
    {
        public System.Guid Id { get; set; }
        public System.Guid AssessmentId { get; set; }
        public System.Guid WebScanTypeId { get; set; }
        public string SearchString { get; set; }
        public bool NegativeInfoFound { get; set; }
        public string Comment { get; set; }
    
        public virtual AssessmentCustomer AssessmentCustomer { get; set; }
        public virtual WebScanType WebScanType { get; set; }
    }
}
