//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentSupplier()
        {
            this.AssessmentSupplierQuestionAnswer = new HashSet<AssessmentSupplierQuestionAnswer>();
            this.AssessmentSupplierWebScan = new HashSet<AssessmentSupplierWebScan>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid AssessmentTypeId { get; set; }
        public System.Guid AssessorId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public string Site { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<System.Guid> VersionId { get; set; }
        public string Commodity { get; set; }
        public Nullable<System.Guid> CaseTypeId { get; set; }
        public Nullable<System.Guid> SectorId { get; set; }
        public string Buyer { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<double> PerformanceRating { get; set; }
        public Nullable<double> RiskRating { get; set; }
        public string RatingComment { get; set; }
        public bool Complete { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public System.Guid ChangedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> SupplyChainID { get; set; }
    
        public virtual AssessmentType AssessmentType { get; set; }
        public virtual CaseType CaseType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual User User2 { get; set; }
        public virtual Version Version { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSupplierQuestionAnswer> AssessmentSupplierQuestionAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSupplierWebScan> AssessmentSupplierWebScan { get; set; }
        public virtual SupplyChain SupplyChain { get; set; }
    }
}
