//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentTransactionType
    {
        public System.Guid Id { get; set; }
        public System.Guid AssessmentCustomerId { get; set; }
        public System.Guid TransactionTypeId { get; set; }
    
        public virtual AssessmentCustomer AssessmentCustomer { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
