//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSRToolContext : DbContext
    {
        public CSRToolContext()
            : base("name=CSRToolContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OfferType> OfferType { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<AssessmentCustomer> AssessmentCustomer { get; set; }
        public virtual DbSet<AssessmentCustomerQuestionAnswer> AssessmentCustomerQuestionAnswer { get; set; }
        public virtual DbSet<AssessmentCustomerWebScan> AssessmentCustomerWebScan { get; set; }
        public virtual DbSet<AssessmentOfferType> AssessmentOfferType { get; set; }
        public virtual DbSet<AssessmentSupplier> AssessmentSupplier { get; set; }
        public virtual DbSet<AssessmentSupplierQuestionAnswer> AssessmentSupplierQuestionAnswer { get; set; }
        public virtual DbSet<AssessmentSupplierWebScan> AssessmentSupplierWebScan { get; set; }
        public virtual DbSet<AssessmentTransactionType> AssessmentTransactionType { get; set; }
        public virtual DbSet<AssessmentType> AssessmentType { get; set; }
        public virtual DbSet<CaseType> CaseType { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Index> Index { get; set; }
        public virtual DbSet<IndexType> IndexType { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswer { get; set; }
        public virtual DbSet<RiskCategory> RiskCategory { get; set; }
        public virtual DbSet<RiskCategoryIndexType> RiskCategoryIndexType { get; set; }
        public virtual DbSet<RiskCategoryQuestion> RiskCategoryQuestion { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Territory> Territory { get; set; }
        public virtual DbSet<TerritoryType> TerritoryType { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<WebScanType> WebScanType { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<AssessmentTypeQuestion> AssessmentTypeQuestion { get; set; }
        public virtual DbSet<SupplyChain> SupplyChain { get; set; }
    }
}
