//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Index
    {
        public System.Guid Id { get; set; }
        public System.Guid IndexTypeId { get; set; }
        public System.Guid TerritoryId { get; set; }
        public System.Guid VersionId { get; set; }
        public decimal Value { get; set; }
    
        public virtual IndexType IndexType { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual Version Version { get; set; }
    }
}
