//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionAnswer()
        {
            this.AssessmentCustomerQuestionAnswer = new HashSet<AssessmentCustomerQuestionAnswer>();
            this.AssessmentSupplierQuestionAnswer = new HashSet<AssessmentSupplierQuestionAnswer>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AnswerId { get; set; }
        public System.Guid QuestionId { get; set; }
    
        public virtual Answer Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCustomerQuestionAnswer> AssessmentCustomerQuestionAnswer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSupplierQuestionAnswer> AssessmentSupplierQuestionAnswer { get; set; }
        public virtual Question Question { get; set; }
    }
}
