//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRTool.Dependencies.Repositories.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskCategoryIndexType
    {
        public System.Guid Id { get; set; }
        public System.Guid RiskCategoryId { get; set; }
        public System.Guid IndexTypeId { get; set; }
        public System.DateTime Created { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime Changed { get; set; }
        public System.Guid ChangedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual IndexType IndexType { get; set; }
        public virtual RiskCategory RiskCategory { get; set; }
    }
}
