//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSRToolWebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSRToolWebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part III: Additional Checks.
        /// </summary>
        public static string AdditionalChecksTitle {
            get {
                return ResourceManager.GetString("AdditionalChecksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessor.
        /// </summary>
        public static string AssessorLabel {
            get {
                return ResourceManager.GetString("AssessorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string AuditCommentLabel {
            get {
                return ResourceManager.GetString("AuditCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused the Audit.
        /// </summary>
        public static string AuditCommentSelection01 {
            get {
                return ResourceManager.GetString("AuditCommentSelection01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than three major deviations.
        /// </summary>
        public static string AuditCommentSelection02 {
            get {
                return ResourceManager.GetString("AuditCommentSelection02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major deviations and performance clearly below country and industry average.
        /// </summary>
        public static string AuditCommentSelection03 {
            get {
                return ResourceManager.GetString("AuditCommentSelection03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No major deviations and performance in line with country and industry average.
        /// </summary>
        public static string AuditCommentSelection04 {
            get {
                return ResourceManager.GetString("AuditCommentSelection04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance significantly over average for industry and country, good example.
        /// </summary>
        public static string AuditCommentSelection05 {
            get {
                return ResourceManager.GetString("AuditCommentSelection05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor.
        /// </summary>
        public static string AuditorLabel {
            get {
                return ResourceManager.GetString("AuditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string AuditTitle {
            get {
                return ResourceManager.GetString("AuditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        public static string BuyerLabel {
            get {
                return ResourceManager.GetString("BuyerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string CaseTypeLabel {
            get {
                return ResourceManager.GetString("CaseTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity.
        /// </summary>
        public static string CommodityLabel {
            get {
                return ResourceManager.GetString("CommodityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local environmental impact.
        /// </summary>
        public static string CountryRiskFactor01 {
            get {
                return ResourceManager.GetString("CountryRiskFactor01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child labour.
        /// </summary>
        public static string CountryRiskFactor02 {
            get {
                return ResourceManager.GetString("CountryRiskFactor02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced or involuntary labour.
        /// </summary>
        public static string CountryRiskFactor03 {
            get {
                return ResourceManager.GetString("CountryRiskFactor03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrimination in the work place.
        /// </summary>
        public static string CountryRiskFactor04 {
            get {
                return ResourceManager.GetString("CountryRiskFactor04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minority rights.
        /// </summary>
        public static string CountryRiskFactor05 {
            get {
                return ResourceManager.GetString("CountryRiskFactor05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupational health and safety.
        /// </summary>
        public static string CountryRiskFactor06 {
            get {
                return ResourceManager.GetString("CountryRiskFactor06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freedom of assembly.
        /// </summary>
        public static string CountryRiskFactor07 {
            get {
                return ResourceManager.GetString("CountryRiskFactor07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freedom of opinion and expression.
        /// </summary>
        public static string CountryRiskFactor08 {
            get {
                return ResourceManager.GetString("CountryRiskFactor08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade compliance.
        /// </summary>
        public static string CountryRiskFactor09 {
            get {
                return ResourceManager.GetString("CountryRiskFactor09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corruption.
        /// </summary>
        public static string CountryRiskFactor10 {
            get {
                return ResourceManager.GetString("CountryRiskFactor10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate governance.
        /// </summary>
        public static string CountryRiskFactor11 {
            get {
                return ResourceManager.GetString("CountryRiskFactor11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Democratic governance.
        /// </summary>
        public static string CountryRiskFactor12 {
            get {
                return ResourceManager.GetString("CountryRiskFactor12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country risk.
        /// </summary>
        public static string CountryRiskTitle {
            get {
                return ResourceManager.GetString("CountryRiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Assessment Form.
        /// </summary>
        public static string CustomerAssessmentFormTitle {
            get {
                return ResourceManager.GetString("CustomerAssessmentFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business arrangements.
        /// </summary>
        public static string CustomerLabel {
            get {
                return ResourceManager.GetString("CustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerNameLabel {
            get {
                return ResourceManager.GetString("CustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS.
        /// </summary>
        public static string DUNSLabel {
            get {
                return ResourceManager.GetString("DUNSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Customer.
        /// </summary>
        public static string ExistingCustomer {
            get {
                return ResourceManager.GetString("ExistingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Supplier.
        /// </summary>
        public static string ExistingSupplier {
            get {
                return ResourceManager.GetString("ExistingSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Risk Assessment.
        /// </summary>
        public static string FirstRiskAssessmentTitle {
            get {
                return ResourceManager.GetString("FirstRiskAssessmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralInformationTitle {
            get {
                return ResourceManager.GetString("GeneralInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string NewAssessmentTitle {
            get {
                return ResourceManager.GetString("NewAssessmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Supplier.
        /// </summary>
        public static string NewSupplier {
            get {
                return ResourceManager.GetString("NewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string OfferLabel {
            get {
                return ResourceManager.GetString("OfferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part II: Performance.
        /// </summary>
        public static string PerformanceTitle {
            get {
                return ResourceManager.GetString("PerformanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project or site name.
        /// </summary>
        public static string ProjectNameLabel {
            get {
                return ResourceManager.GetString("ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental management.
        /// </summary>
        public static string Question01 {
            get {
                return ResourceManager.GetString("Question01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known environmental issues.
        /// </summary>
        public static string Question01Answer01 {
            get {
                return ResourceManager.GetString("Question01Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documented environmental instructions.
        /// </summary>
        public static string Question01Answer02 {
            get {
                return ResourceManager.GetString("Question01Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some environmental instructions available and visible.
        /// </summary>
        public static string Question01Answer03 {
            get {
                return ResourceManager.GetString("Question01Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appears to have a well structured work with environment.
        /// </summary>
        public static string Question01Answer04 {
            get {
                return ResourceManager.GetString("Question01Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question01Answer05 {
            get {
                return ResourceManager.GetString("Question01Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupational safety &amp; health procedures.
        /// </summary>
        public static string Question02 {
            get {
                return ResourceManager.GetString("Question02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known health &amp; safety issues.
        /// </summary>
        public static string Question02Answer01 {
            get {
                return ResourceManager.GetString("Question02Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documented safety and health instructions.
        /// </summary>
        public static string Question02Answer02 {
            get {
                return ResourceManager.GetString("Question02Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some safety and health instructions available and visible.
        /// </summary>
        public static string Question02Answer03 {
            get {
                return ResourceManager.GetString("Question02Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appears to have a well structured work with safety and health.
        /// </summary>
        public static string Question02Answer04 {
            get {
                return ResourceManager.GetString("Question02Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question02Answer05 {
            get {
                return ResourceManager.GetString("Question02Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human rights program.
        /// </summary>
        public static string Question03 {
            get {
                return ResourceManager.GetString("Question03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known human rights issues.
        /// </summary>
        public static string Question03Answer01 {
            get {
                return ResourceManager.GetString("Question03Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information that the customer supports human rights..
        /// </summary>
        public static string Question03Answer02 {
            get {
                return ResourceManager.GetString("Question03Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some info supporting fundamentals of human rights..
        /// </summary>
        public static string Question03Answer03 {
            get {
                return ResourceManager.GetString("Question03Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public policy and/or formal program to observe the fundamentals of human rights..
        /// </summary>
        public static string Question03Answer04 {
            get {
                return ResourceManager.GetString("Question03Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question03Answer05 {
            get {
                return ResourceManager.GetString("Question03Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-bribery and anti-corruption.
        /// </summary>
        public static string Question04 {
            get {
                return ResourceManager.GetString("Question04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scania sales responsible not trained in Doing things right or similar..
        /// </summary>
        public static string Question04Answer01 {
            get {
                return ResourceManager.GetString("Question04Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scania sales responsible trained in Doing things right..
        /// </summary>
        public static string Question04Answer02 {
            get {
                return ResourceManager.GetString("Question04Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site location (environment).
        /// </summary>
        public static string Question05 {
            get {
                return ResourceManager.GetString("Question05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located in an environmentally sensitive area.
        /// </summary>
        public static string Question05Answer01 {
            get {
                return ResourceManager.GetString("Question05Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not located in an environmentally sensitive area.
        /// </summary>
        public static string Question05Answer02 {
            get {
                return ResourceManager.GetString("Question05Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question05Answer03 {
            get {
                return ResourceManager.GetString("Question05Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site knowledge.
        /// </summary>
        public static string Question06 {
            get {
                return ResourceManager.GetString("Question06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Question06Answer01 {
            get {
                return ResourceManager.GetString("Question06Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No visit, but pictures from site and written information received.
        /// </summary>
        public static string Question06Answer02 {
            get {
                return ResourceManager.GetString("Question06Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site has been visited but not enough information about labour laws and working conditions for front line workers.
        /// </summary>
        public static string Question06Answer03 {
            get {
                return ResourceManager.GetString("Question06Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site has been visited and it appear that labour laws are followed and working conditions acceptable.
        /// </summary>
        public static string Question06Answer04 {
            get {
                return ResourceManager.GetString("Question06Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there a clear explanation about why this agent´s services are needed?.
        /// </summary>
        public static string Question07 {
            get {
                return ResourceManager.GetString("Question07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question07Answer01 {
            get {
                return ResourceManager.GetString("Question07Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question07Answer02 {
            get {
                return ResourceManager.GetString("Question07Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question07Answer03 {
            get {
                return ResourceManager.GetString("Question07Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have I signed an agreement with the agent?.
        /// </summary>
        public static string Question08 {
            get {
                return ResourceManager.GetString("Question08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question08Answer01 {
            get {
                return ResourceManager.GetString("Question08Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question08Answer02 {
            get {
                return ResourceManager.GetString("Question08Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question08Answer03 {
            get {
                return ResourceManager.GetString("Question08Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have I properly and accurately documented and recorded all payments to the agent?.
        /// </summary>
        public static string Question09 {
            get {
                return ResourceManager.GetString("Question09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question09Answer01 {
            get {
                return ResourceManager.GetString("Question09Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question09Answer02 {
            get {
                return ResourceManager.GetString("Question09Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question09Answer03 {
            get {
                return ResourceManager.GetString("Question09Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there evidence that the agent has performed the service?.
        /// </summary>
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question10Answer01 {
            get {
                return ResourceManager.GetString("Question10Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question10Answer02 {
            get {
                return ResourceManager.GetString("Question10Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question10Answer03 {
            get {
                return ResourceManager.GetString("Question10Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have I received a correct and verified end user certificate?.
        /// </summary>
        public static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question11Answer01 {
            get {
                return ResourceManager.GetString("Question11Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question11Answer02 {
            get {
                return ResourceManager.GetString("Question11Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question11Answer03 {
            get {
                return ResourceManager.GetString("Question11Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the sales person aware of the segment ethical guidelines?.
        /// </summary>
        public static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question12Answer01 {
            get {
                return ResourceManager.GetString("Question12Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question12Answer02 {
            get {
                return ResourceManager.GetString("Question12Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question12Answer03 {
            get {
                return ResourceManager.GetString("Question12Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethical business behaviour.
        /// </summary>
        public static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier clearly violates Scania´s principles of ethical business..
        /// </summary>
        public static string Question13Answer01 {
            get {
                return ResourceManager.GetString("Question13Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier has no policies that supports ethical business behaviour.
        /// </summary>
        public static string Question13Answer02 {
            get {
                return ResourceManager.GetString("Question13Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier has policies that supports ethical business behaviour.
        /// </summary>
        public static string Question13Answer03 {
            get {
                return ResourceManager.GetString("Question13Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier has public policies and programs including training of employees .
        /// </summary>
        public static string Question13Answer04 {
            get {
                return ResourceManager.GetString("Question13Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question13Answer05 {
            get {
                return ResourceManager.GetString("Question13Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the segment specific requirements.
        /// </summary>
        public static string Question14 {
            get {
                return ResourceManager.GetString("Question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question14Answer01 {
            get {
                return ResourceManager.GetString("Question14Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question14Answer02 {
            get {
                return ResourceManager.GetString("Question14Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None exists.
        /// </summary>
        public static string Question14Answer03 {
            get {
                return ResourceManager.GetString("Question14Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question14Answer04 {
            get {
                return ResourceManager.GetString("Question14Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Assessment.
        /// </summary>
        public static string Question15 {
            get {
                return ResourceManager.GetString("Question15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to do the SAQ but didn´t submit.
        /// </summary>
        public static string Question15Answer01 {
            get {
                return ResourceManager.GetString("Question15Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall rating below 25%.
        /// </summary>
        public static string Question15Answer02 {
            get {
                return ResourceManager.GetString("Question15Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rating below 25%.
        /// </summary>
        public static string Question15Answer03 {
            get {
                return ResourceManager.GetString("Question15Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall rating 25-50%.
        /// </summary>
        public static string Question15Answer04 {
            get {
                return ResourceManager.GetString("Question15Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall rating 50-75%.
        /// </summary>
        public static string Question15Answer05 {
            get {
                return ResourceManager.GetString("Question15Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall rating 75-100%.
        /// </summary>
        public static string Question15Answer06 {
            get {
                return ResourceManager.GetString("Question15Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string Question16 {
            get {
                return ResourceManager.GetString("Question16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused the Audit.
        /// </summary>
        public static string Question16Answer01 {
            get {
                return ResourceManager.GetString("Question16Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than three major deviations.
        /// </summary>
        public static string Question16Answer02 {
            get {
                return ResourceManager.GetString("Question16Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major deviations and performance clearly below country and industry average.
        /// </summary>
        public static string Question16Answer03 {
            get {
                return ResourceManager.GetString("Question16Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No major deviations and performance in line with country and industry average.
        /// </summary>
        public static string Question16Answer04 {
            get {
                return ResourceManager.GetString("Question16Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance significantly over average for industry and country, good example.
        /// </summary>
        public static string Question16Answer05 {
            get {
                return ResourceManager.GetString("Question16Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading of demands to subtiers.
        /// </summary>
        public static string Question17 {
            get {
                return ResourceManager.GetString("Question17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supplier policy or supplier code of conduct.
        /// </summary>
        public static string Question17Answer01 {
            get {
                return ResourceManager.GetString("Question17Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier policy or code of conduct exist, but doesn´t cover all areas.
        /// </summary>
        public static string Question17Answer02 {
            get {
                return ResourceManager.GetString("Question17Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier policy or code of conduct cover all valid areas.
        /// </summary>
        public static string Question17Answer03 {
            get {
                return ResourceManager.GetString("Question17Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier policy or code of conduct cover all plant based purchasing.
        /// </summary>
        public static string Question17Answer04 {
            get {
                return ResourceManager.GetString("Question17Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier policy or code of conduct communicated in contractual terms.
        /// </summary>
        public static string Question17Answer05 {
            get {
                return ResourceManager.GetString("Question17Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract support and processes to ensure effective implementation.
        /// </summary>
        public static string Question17Answer06 {
            get {
                return ResourceManager.GetString("Question17Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question17Answer07 {
            get {
                return ResourceManager.GetString("Question17Answer07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site location (human rights).
        /// </summary>
        public static string Question18 {
            get {
                return ResourceManager.GetString("Question18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including reallocation of people.
        /// </summary>
        public static string Question18Answer01 {
            get {
                return ResourceManager.GetString("Question18Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not including reallocation of people.
        /// </summary>
        public static string Question18Answer02 {
            get {
                return ResourceManager.GetString("Question18Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don´t know.
        /// </summary>
        public static string Question18Answer03 {
            get {
                return ResourceManager.GetString("Question18Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Areas.
        /// </summary>
        public static string Question20 {
            get {
                return ResourceManager.GetString("Question20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low performance.
        /// </summary>
        public static string Question20Answer01 {
            get {
                return ResourceManager.GetString("Question20Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low performance.
        /// </summary>
        public static string Question20Answer02 {
            get {
                return ResourceManager.GetString("Question20Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium performance.
        /// </summary>
        public static string Question20Answer03 {
            get {
                return ResourceManager.GetString("Question20Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        public static string Question20Answer04 {
            get {
                return ResourceManager.GetString("Question20Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very high performance.
        /// </summary>
        public static string Question20Answer05 {
            get {
                return ResourceManager.GetString("Question20Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t know .
        /// </summary>
        public static string Question20Answer06 {
            get {
                return ResourceManager.GetString("Question20Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Management.
        /// </summary>
        public static string Question21 {
            get {
                return ResourceManager.GetString("Question21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low performance.
        /// </summary>
        public static string Question21Answer01 {
            get {
                return ResourceManager.GetString("Question21Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low performance.
        /// </summary>
        public static string Question21Answer02 {
            get {
                return ResourceManager.GetString("Question21Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium performance.
        /// </summary>
        public static string Question21Answer03 {
            get {
                return ResourceManager.GetString("Question21Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        public static string Question21Answer04 {
            get {
                return ResourceManager.GetString("Question21Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very high performance.
        /// </summary>
        public static string Question21Answer05 {
            get {
                return ResourceManager.GetString("Question21Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t know .
        /// </summary>
        public static string Question21Answer06 {
            get {
                return ResourceManager.GetString("Question21Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental Sustainability.
        /// </summary>
        public static string Question22 {
            get {
                return ResourceManager.GetString("Question22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low performance.
        /// </summary>
        public static string Question22Answer01 {
            get {
                return ResourceManager.GetString("Question22Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low performance.
        /// </summary>
        public static string Question22Answer02 {
            get {
                return ResourceManager.GetString("Question22Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium performance.
        /// </summary>
        public static string Question22Answer03 {
            get {
                return ResourceManager.GetString("Question22Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        public static string Question22Answer04 {
            get {
                return ResourceManager.GetString("Question22Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very high performance.
        /// </summary>
        public static string Question22Answer05 {
            get {
                return ResourceManager.GetString("Question22Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t know .
        /// </summary>
        public static string Question22Answer06 {
            get {
                return ResourceManager.GetString("Question22Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Conduct and Compliance.
        /// </summary>
        public static string Question23 {
            get {
                return ResourceManager.GetString("Question23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low performance.
        /// </summary>
        public static string Question23Answer01 {
            get {
                return ResourceManager.GetString("Question23Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low performance.
        /// </summary>
        public static string Question23Answer02 {
            get {
                return ResourceManager.GetString("Question23Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium performance.
        /// </summary>
        public static string Question23Answer03 {
            get {
                return ResourceManager.GetString("Question23Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        public static string Question23Answer04 {
            get {
                return ResourceManager.GetString("Question23Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very high performance.
        /// </summary>
        public static string Question23Answer05 {
            get {
                return ResourceManager.GetString("Question23Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t know .
        /// </summary>
        public static string Question23Answer06 {
            get {
                return ResourceManager.GetString("Question23Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Sustainability.
        /// </summary>
        public static string Question24 {
            get {
                return ResourceManager.GetString("Question24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low performance.
        /// </summary>
        public static string Question24Answer01 {
            get {
                return ResourceManager.GetString("Question24Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low performance.
        /// </summary>
        public static string Question24Answer02 {
            get {
                return ResourceManager.GetString("Question24Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium performance.
        /// </summary>
        public static string Question24Answer03 {
            get {
                return ResourceManager.GetString("Question24Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        public static string Question24Answer04 {
            get {
                return ResourceManager.GetString("Question24Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very high performance.
        /// </summary>
        public static string Question24Answer05 {
            get {
                return ResourceManager.GetString("Question24Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t know .
        /// </summary>
        public static string Question24Answer06 {
            get {
                return ResourceManager.GetString("Question24Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company management.
        /// </summary>
        public static string Question26 {
            get {
                return ResourceManager.GetString("Question26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low performance.
        /// </summary>
        public static string Question26Answer01 {
            get {
                return ResourceManager.GetString("Question26Answer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low performance.
        /// </summary>
        public static string Question26Answer02 {
            get {
                return ResourceManager.GetString("Question26Answer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium performance.
        /// </summary>
        public static string Question26Answer03 {
            get {
                return ResourceManager.GetString("Question26Answer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        public static string Question26Answer04 {
            get {
                return ResourceManager.GetString("Question26Answer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very high performance.
        /// </summary>
        public static string Question26Answer05 {
            get {
                return ResourceManager.GetString("Question26Answer05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t know .
        /// </summary>
        public static string Question26Answer06 {
            get {
                return ResourceManager.GetString("Question26Answer06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Sales Person.
        /// </summary>
        public static string ResponsibleSalesPersonLabel {
            get {
                return ResourceManager.GetString("ResponsibleSalesPersonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Assessment questions.
        /// </summary>
        public static string RiskAssessmentQuestionsTitle {
            get {
                return ResourceManager.GetString("RiskAssessmentQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part I: Risk.
        /// </summary>
        public static string RiskTitle {
            get {
                return ResourceManager.GetString("RiskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sector.
        /// </summary>
        public static string SalesController_GetSectors_Select {
            get {
                return ResourceManager.GetString("SalesController_GetSectors_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string SalesController_GetTerritories_Select {
            get {
                return ResourceManager.GetString("SalesController_GetTerritories_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select comment.
        /// </summary>
        public static string SalesController_GetWebScan_Select {
            get {
                return ResourceManager.GetString("SalesController_GetWebScan_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling department.
        /// </summary>
        public static string ScaniaCompanyDepartmentLabel {
            get {
                return ResourceManager.GetString("ScaniaCompanyDepartmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scania specific.
        /// </summary>
        public static string ScaniaSpecificTitle {
            get {
                return ResourceManager.GetString("ScaniaSpecificTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper &amp; pulp.
        /// </summary>
        public static string Sector01Name {
            get {
                return ResourceManager.GetString("Sector01Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining.
        /// </summary>
        public static string Sector02Name {
            get {
                return ResourceManager.GetString("Sector02Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction, building.
        /// </summary>
        public static string Sector03Name {
            get {
                return ResourceManager.GetString("Sector03Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron and steel.
        /// </summary>
        public static string Sector04Name {
            get {
                return ResourceManager.GetString("Sector04Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical.
        /// </summary>
        public static string Sector05Name {
            get {
                return ResourceManager.GetString("Sector05Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textiles and leather.
        /// </summary>
        public static string Sector06Name {
            get {
                return ResourceManager.GetString("Sector06Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel, lubricants etc..
        /// </summary>
        public static string Sector07Name {
            get {
                return ResourceManager.GetString("Sector07Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic services.
        /// </summary>
        public static string Sector08Name {
            get {
                return ResourceManager.GetString("Sector08Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastics, foam etc..
        /// </summary>
        public static string Sector09Name {
            get {
                return ResourceManager.GetString("Sector09Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber.
        /// </summary>
        public static string Sector10Name {
            get {
                return ResourceManager.GetString("Sector10Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical.
        /// </summary>
        public static string Sector11Name {
            get {
                return ResourceManager.GetString("Sector11Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string Sector12Name {
            get {
                return ResourceManager.GetString("Sector12Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other sector (no significant added risk).
        /// </summary>
        public static string Sector13Name {
            get {
                return ResourceManager.GetString("Sector13Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector or Industry.
        /// </summary>
        public static string SectorLabel {
            get {
                return ResourceManager.GetString("SectorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string SegmentLabel {
            get {
                return ResourceManager.GetString("SegmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site knowledge.
        /// </summary>
        public static string SiteKnowledgeLabel {
            get {
                return ResourceManager.GetString("SiteKnowledgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string SiteLabel {
            get {
                return ResourceManager.GetString("SiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string SiteNameLabel {
            get {
                return ResourceManager.GetString("SiteNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific question.
        /// </summary>
        public static string SpecificQuestionsTitle {
            get {
                return ResourceManager.GetString("SpecificQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Assessment Form.
        /// </summary>
        public static string SupplierAssessmentFormTitle {
            get {
                return ResourceManager.GetString("SupplierAssessmentFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Self Assessment questions.
        /// </summary>
        public static string SupplierAssessmentQuestionsTitle {
            get {
                return ResourceManager.GetString("SupplierAssessmentQuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SupplierLabel {
            get {
                return ResourceManager.GetString("SupplierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SupplyChain1Name {
            get {
                return ResourceManager.GetString("SupplyChain1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No visits, pictures from site and written info received.
        /// </summary>
        public static string SupplyChain2Name {
            get {
                return ResourceManager.GetString("SupplyChain2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited site, lacking info about labour laws &amp; working conditions.
        /// </summary>
        public static string SupplyChain3Name {
            get {
                return ResourceManager.GetString("SupplyChain3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited site, labour laws are followed &amp; working conditions acceptable.
        /// </summary>
        public static string SupplyChain4Name {
            get {
                return ResourceManager.GetString("SupplyChain4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply chain.
        /// </summary>
        public static string SupplyChainLabel {
            get {
                return ResourceManager.GetString("SupplyChainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Scan 1.
        /// </summary>
        public static string WebScan1Label {
            get {
                return ResourceManager.GetString("WebScan1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Scan 2.
        /// </summary>
        public static string WebScan2Label {
            get {
                return ResourceManager.GetString("WebScan2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No negative information found.
        /// </summary>
        public static string WebScanCheckLabel {
            get {
                return ResourceManager.GetString("WebScanCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Scan.
        /// </summary>
        public static string WebScanTitle {
            get {
                return ResourceManager.GetString("WebScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string WebSearchCommentLabel {
            get {
                return ResourceManager.GetString("WebSearchCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative information found, credible source.
        /// </summary>
        public static string WebSearchCommentSelection01 {
            get {
                return ResourceManager.GetString("WebSearchCommentSelection01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative information found, non credible source.
        /// </summary>
        public static string WebSearchCommentSelection02 {
            get {
                return ResourceManager.GetString("WebSearchCommentSelection02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No negative information found.
        /// </summary>
        public static string WebSearchCommentSelection03 {
            get {
                return ResourceManager.GetString("WebSearchCommentSelection03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not use it)No negative information found.
        /// </summary>
        public static string WebSearchCommentSelection04 {
            get {
                return ResourceManager.GetString("WebSearchCommentSelection04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &amp; paste in search eng..
        /// </summary>
        public static string WebSearchInstruction {
            get {
                return ResourceManager.GetString("WebSearchInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web search.
        /// </summary>
        public static string WebSearchTitle {
            get {
                return ResourceManager.GetString("WebSearchTitle", resourceCulture);
            }
        }
    }
}
